sudo: false
language: node_js
node_js: 
  - "node"
services:
  - postgresql
addons:
  postgresql: "9.4"
cache:
  directories:
    - "node_modules"
install:
  - npm ci
after_success:
  - npm run coverage
notifications:
  email: false