sudo: false
language: node_js
node_js: 
  - "node"
services:
  - postgresql
addons:
  postgresql: "9.4"
cache:
  directories:
    - "node_modules"
install:
  - npm ci
before_script:
  - psql -c 'drop database if exists propertypro_test;' -U postgres
  - psql -c 'create database propertypro_test;' -U postgres
  - npm run seeder
after_success:
  - npm run coverage
notifications:
  email: false