sudo: false
language: node_js
node_js: 
  - "node"
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'drop database if exists propertypro;' -U farce
  - psql -c 'create database propertypro;' -U farce
cache:
  directories:
    - "node_modules"
install:
  - npm ci
after_success:
  - npm run coverage
notifications:
  email: false